name: ColorfulChat
main: kim.minecraft.colorfulchat.ColorfulChat
version: 1.0-SNAPSHOT
author: shaokeyibb & NaturalSharp

commands:
  colorfulchat:
    description: "彩色聊天"
    usage: "/colorfulchat 开关彩色聊天"
    permission: "colorfulchat.use"
    permission-message: "§c您没有权限执行此命令"